//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServicePrestamo {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePrestamo.WebServicePrestamoSoap")]
    public interface WebServicePrestamoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webAnadirPrestamo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void webAnadirPrestamo(string rut, string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webAnadirPrestamo", ReplyAction="*")]
        System.Threading.Tasks.Task webAnadirPrestamoAsync(string rut, string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webMostrarPrestamos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet webMostrarPrestamos(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webMostrarPrestamos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> webMostrarPrestamosAsync(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webMostrarPrestamosGeneral", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet webMostrarPrestamosGeneral();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webMostrarPrestamosGeneral", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> webMostrarPrestamosGeneralAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webMostrarPrestamosTotal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet webMostrarPrestamosTotal();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webMostrarPrestamosTotal", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> webMostrarPrestamosTotalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webFinalizarPrestamo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void webFinalizarPrestamo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webFinalizarPrestamo", ReplyAction="*")]
        System.Threading.Tasks.Task webFinalizarPrestamoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webVerificarEstadoPrestamos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet webVerificarEstadoPrestamos(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webVerificarEstadoPrestamos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> webVerificarEstadoPrestamosAsync(string rut);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicePrestamoSoapChannel : CapaGUI.ServicePrestamo.WebServicePrestamoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicePrestamoSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServicePrestamo.WebServicePrestamoSoap>, CapaGUI.ServicePrestamo.WebServicePrestamoSoap {
        
        public WebServicePrestamoSoapClient() {
        }
        
        public WebServicePrestamoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicePrestamoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePrestamoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePrestamoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void webAnadirPrestamo(string rut, string isbn) {
            base.Channel.webAnadirPrestamo(rut, isbn);
        }
        
        public System.Threading.Tasks.Task webAnadirPrestamoAsync(string rut, string isbn) {
            return base.Channel.webAnadirPrestamoAsync(rut, isbn);
        }
        
        public System.Data.DataSet webMostrarPrestamos(string rut) {
            return base.Channel.webMostrarPrestamos(rut);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> webMostrarPrestamosAsync(string rut) {
            return base.Channel.webMostrarPrestamosAsync(rut);
        }
        
        public System.Data.DataSet webMostrarPrestamosGeneral() {
            return base.Channel.webMostrarPrestamosGeneral();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> webMostrarPrestamosGeneralAsync() {
            return base.Channel.webMostrarPrestamosGeneralAsync();
        }
        
        public System.Data.DataSet webMostrarPrestamosTotal() {
            return base.Channel.webMostrarPrestamosTotal();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> webMostrarPrestamosTotalAsync() {
            return base.Channel.webMostrarPrestamosTotalAsync();
        }
        
        public void webFinalizarPrestamo(int id) {
            base.Channel.webFinalizarPrestamo(id);
        }
        
        public System.Threading.Tasks.Task webFinalizarPrestamoAsync(int id) {
            return base.Channel.webFinalizarPrestamoAsync(id);
        }
        
        public System.Data.DataSet webVerificarEstadoPrestamos(string rut) {
            return base.Channel.webVerificarEstadoPrestamos(rut);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> webVerificarEstadoPrestamosAsync(string rut) {
            return base.Channel.webVerificarEstadoPrestamosAsync(rut);
        }
    }
}
