//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceEmpleado {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CapaGUI.ServiceEmpleado.Empleado))]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fecha_nacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        private int Numero_telefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fecha_creacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Apaterno {
            get {
                return this.ApaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApaternoField, value) != true)) {
                    this.ApaternoField = value;
                    this.RaisePropertyChanged("Apaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Amaterno {
            get {
                return this.AmaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.AmaternoField, value) != true)) {
                    this.AmaternoField = value;
                    this.RaisePropertyChanged("Amaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Rut {
            get {
                return this.RutField;
            }
            set {
                if ((object.ReferenceEquals(this.RutField, value) != true)) {
                    this.RutField = value;
                    this.RaisePropertyChanged("Rut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Fecha_nacimiento {
            get {
                return this.Fecha_nacimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.Fecha_nacimientoField, value) != true)) {
                    this.Fecha_nacimientoField = value;
                    this.RaisePropertyChanged("Fecha_nacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int Numero_telefono {
            get {
                return this.Numero_telefonoField;
            }
            set {
                if ((this.Numero_telefonoField.Equals(value) != true)) {
                    this.Numero_telefonoField = value;
                    this.RaisePropertyChanged("Numero_telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Fecha_creacion {
            get {
                return this.Fecha_creacionField;
            }
            set {
                if ((object.ReferenceEquals(this.Fecha_creacionField, value) != true)) {
                    this.Fecha_creacionField = value;
                    this.RaisePropertyChanged("Fecha_creacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Empleado : CapaGUI.ServiceEmpleado.Usuario {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fecha_ingresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tipo_empleadoField;
        
        private bool EstadoField;
        
        private bool AdministradorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Fecha_ingreso {
            get {
                return this.Fecha_ingresoField;
            }
            set {
                if ((object.ReferenceEquals(this.Fecha_ingresoField, value) != true)) {
                    this.Fecha_ingresoField = value;
                    this.RaisePropertyChanged("Fecha_ingreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Tipo_empleado {
            get {
                return this.Tipo_empleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.Tipo_empleadoField, value) != true)) {
                    this.Tipo_empleadoField = value;
                    this.RaisePropertyChanged("Tipo_empleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool Administrador {
            get {
                return this.AdministradorField;
            }
            set {
                if ((this.AdministradorField.Equals(value) != true)) {
                    this.AdministradorField = value;
                    this.RaisePropertyChanged("Administrador");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEmpleado.WebServiceEmpleadoSoap")]
    public interface WebServiceEmpleadoSoap {
        
        // CODEGEN: Generating message contract since element name empleado from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webAnadirEmpleado", ReplyAction="*")]
        CapaGUI.ServiceEmpleado.webAnadirEmpleadoResponse webAnadirEmpleado(CapaGUI.ServiceEmpleado.webAnadirEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webAnadirEmpleado", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceEmpleado.webAnadirEmpleadoResponse> webAnadirEmpleadoAsync(CapaGUI.ServiceEmpleado.webAnadirEmpleadoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webAnadirEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webAnadirEmpleado", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceEmpleado.webAnadirEmpleadoRequestBody Body;
        
        public webAnadirEmpleadoRequest() {
        }
        
        public webAnadirEmpleadoRequest(CapaGUI.ServiceEmpleado.webAnadirEmpleadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class webAnadirEmpleadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaGUI.ServiceEmpleado.Empleado empleado;
        
        public webAnadirEmpleadoRequestBody() {
        }
        
        public webAnadirEmpleadoRequestBody(CapaGUI.ServiceEmpleado.Empleado empleado) {
            this.empleado = empleado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webAnadirEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webAnadirEmpleadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceEmpleado.webAnadirEmpleadoResponseBody Body;
        
        public webAnadirEmpleadoResponse() {
        }
        
        public webAnadirEmpleadoResponse(CapaGUI.ServiceEmpleado.webAnadirEmpleadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class webAnadirEmpleadoResponseBody {
        
        public webAnadirEmpleadoResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceEmpleadoSoapChannel : CapaGUI.ServiceEmpleado.WebServiceEmpleadoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceEmpleadoSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceEmpleado.WebServiceEmpleadoSoap>, CapaGUI.ServiceEmpleado.WebServiceEmpleadoSoap {
        
        public WebServiceEmpleadoSoapClient() {
        }
        
        public WebServiceEmpleadoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceEmpleadoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceEmpleadoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceEmpleadoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceEmpleado.webAnadirEmpleadoResponse CapaGUI.ServiceEmpleado.WebServiceEmpleadoSoap.webAnadirEmpleado(CapaGUI.ServiceEmpleado.webAnadirEmpleadoRequest request) {
            return base.Channel.webAnadirEmpleado(request);
        }
        
        public void webAnadirEmpleado(CapaGUI.ServiceEmpleado.Empleado empleado) {
            CapaGUI.ServiceEmpleado.webAnadirEmpleadoRequest inValue = new CapaGUI.ServiceEmpleado.webAnadirEmpleadoRequest();
            inValue.Body = new CapaGUI.ServiceEmpleado.webAnadirEmpleadoRequestBody();
            inValue.Body.empleado = empleado;
            CapaGUI.ServiceEmpleado.webAnadirEmpleadoResponse retVal = ((CapaGUI.ServiceEmpleado.WebServiceEmpleadoSoap)(this)).webAnadirEmpleado(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceEmpleado.webAnadirEmpleadoResponse> CapaGUI.ServiceEmpleado.WebServiceEmpleadoSoap.webAnadirEmpleadoAsync(CapaGUI.ServiceEmpleado.webAnadirEmpleadoRequest request) {
            return base.Channel.webAnadirEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceEmpleado.webAnadirEmpleadoResponse> webAnadirEmpleadoAsync(CapaGUI.ServiceEmpleado.Empleado empleado) {
            CapaGUI.ServiceEmpleado.webAnadirEmpleadoRequest inValue = new CapaGUI.ServiceEmpleado.webAnadirEmpleadoRequest();
            inValue.Body = new CapaGUI.ServiceEmpleado.webAnadirEmpleadoRequestBody();
            inValue.Body.empleado = empleado;
            return ((CapaGUI.ServiceEmpleado.WebServiceEmpleadoSoap)(this)).webAnadirEmpleadoAsync(inValue);
        }
    }
}
