//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceMulta {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMulta.WebServiceMultaSoap")]
    public interface WebServiceMultaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webAnadirMulta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void webAnadirMulta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webAnadirMulta", ReplyAction="*")]
        System.Threading.Tasks.Task webAnadirMultaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webmostrarTodasMultasCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet webmostrarTodasMultasCliente(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webmostrarTodasMultasCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> webmostrarTodasMultasClienteAsync(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webMostrarTodasMultas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet webMostrarTodasMultas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webMostrarTodasMultas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> webMostrarTodasMultasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webMostrarMultaCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet webMostrarMultaCliente(string id_multa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webMostrarMultaCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> webMostrarMultaClienteAsync(string id_multa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webMostrarMultaSemana", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet webMostrarMultaSemana();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webMostrarMultaSemana", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> webMostrarMultaSemanaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webMostrarMultaMes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet webMostrarMultaMes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webMostrarMultaMes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> webMostrarMultaMesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webPagarMulta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void webPagarMulta(CapaGUI.ServiceMulta.Multa multa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webPagarMulta", ReplyAction="*")]
        System.Threading.Tasks.Task webPagarMultaAsync(CapaGUI.ServiceMulta.Multa multa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webActualizarMultasImpagas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void webActualizarMultasImpagas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webActualizarMultasImpagas", ReplyAction="*")]
        System.Threading.Tasks.Task webActualizarMultasImpagasAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Multa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int id_multaField;
        
        private string fecha_multaField;
        
        private bool pagadaField;
        
        private int monto_pagoField;
        
        private int dias_atrasoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id_multa {
            get {
                return this.id_multaField;
            }
            set {
                this.id_multaField = value;
                this.RaisePropertyChanged("Id_multa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Fecha_multa {
            get {
                return this.fecha_multaField;
            }
            set {
                this.fecha_multaField = value;
                this.RaisePropertyChanged("Fecha_multa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Pagada {
            get {
                return this.pagadaField;
            }
            set {
                this.pagadaField = value;
                this.RaisePropertyChanged("Pagada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Monto_pago {
            get {
                return this.monto_pagoField;
            }
            set {
                this.monto_pagoField = value;
                this.RaisePropertyChanged("Monto_pago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Dias_atraso {
            get {
                return this.dias_atrasoField;
            }
            set {
                this.dias_atrasoField = value;
                this.RaisePropertyChanged("Dias_atraso");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMultaSoapChannel : CapaGUI.ServiceMulta.WebServiceMultaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMultaSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceMulta.WebServiceMultaSoap>, CapaGUI.ServiceMulta.WebServiceMultaSoap {
        
        public WebServiceMultaSoapClient() {
        }
        
        public WebServiceMultaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMultaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMultaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMultaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void webAnadirMulta() {
            base.Channel.webAnadirMulta();
        }
        
        public System.Threading.Tasks.Task webAnadirMultaAsync() {
            return base.Channel.webAnadirMultaAsync();
        }
        
        public System.Data.DataSet webmostrarTodasMultasCliente(string rut) {
            return base.Channel.webmostrarTodasMultasCliente(rut);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> webmostrarTodasMultasClienteAsync(string rut) {
            return base.Channel.webmostrarTodasMultasClienteAsync(rut);
        }
        
        public System.Data.DataSet webMostrarTodasMultas() {
            return base.Channel.webMostrarTodasMultas();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> webMostrarTodasMultasAsync() {
            return base.Channel.webMostrarTodasMultasAsync();
        }
        
        public System.Data.DataSet webMostrarMultaCliente(string id_multa) {
            return base.Channel.webMostrarMultaCliente(id_multa);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> webMostrarMultaClienteAsync(string id_multa) {
            return base.Channel.webMostrarMultaClienteAsync(id_multa);
        }
        
        public System.Data.DataSet webMostrarMultaSemana() {
            return base.Channel.webMostrarMultaSemana();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> webMostrarMultaSemanaAsync() {
            return base.Channel.webMostrarMultaSemanaAsync();
        }
        
        public System.Data.DataSet webMostrarMultaMes() {
            return base.Channel.webMostrarMultaMes();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> webMostrarMultaMesAsync() {
            return base.Channel.webMostrarMultaMesAsync();
        }
        
        public void webPagarMulta(CapaGUI.ServiceMulta.Multa multa) {
            base.Channel.webPagarMulta(multa);
        }
        
        public System.Threading.Tasks.Task webPagarMultaAsync(CapaGUI.ServiceMulta.Multa multa) {
            return base.Channel.webPagarMultaAsync(multa);
        }
        
        public void webActualizarMultasImpagas() {
            base.Channel.webActualizarMultasImpagas();
        }
        
        public System.Threading.Tasks.Task webActualizarMultasImpagasAsync() {
            return base.Channel.webActualizarMultasImpagasAsync();
        }
    }
}
