//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceCliente {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCliente.WebServiceClienteSoap")]
    public interface WebServiceClienteSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webAnadirCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Usuario))]
        void webAnadirCliente(CapaGUI.ServiceCliente.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webAnadirCliente", ReplyAction="*")]
        System.Threading.Tasks.Task webAnadirClienteAsync(CapaGUI.ServiceCliente.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webMostrarDatosCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Usuario))]
        System.Data.DataSet webMostrarDatosCliente(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webMostrarDatosCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> webMostrarDatosClienteAsync(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webIniciarSesionCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Usuario))]
        System.Data.DataSet webIniciarSesionCliente(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webIniciarSesionCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> webIniciarSesionClienteAsync(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webMostrarTodosClientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Usuario))]
        System.Data.DataSet webMostrarTodosClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webMostrarTodosClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> webMostrarTodosClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webMostrarClienteFiltro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Usuario))]
        System.Data.DataSet webMostrarClienteFiltro(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webMostrarClienteFiltro", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> webMostrarClienteFiltroAsync(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webActualizarPrestamosMultas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Usuario))]
        void webActualizarPrestamosMultas(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webActualizarPrestamosMultas", ReplyAction="*")]
        System.Threading.Tasks.Task webActualizarPrestamosMultasAsync(string rut);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cliente : Usuario {
        
        private int cant_prestamosField;
        
        private bool multa_vigenteField;
        
        private bool miembroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Cant_prestamos {
            get {
                return this.cant_prestamosField;
            }
            set {
                this.cant_prestamosField = value;
                this.RaisePropertyChanged("Cant_prestamos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Multa_vigente {
            get {
                return this.multa_vigenteField;
            }
            set {
                this.multa_vigenteField = value;
                this.RaisePropertyChanged("Multa_vigente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Miembro {
            get {
                return this.miembroField;
            }
            set {
                this.miembroField = value;
                this.RaisePropertyChanged("Miembro");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cliente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private string apaternoField;
        
        private string amaternoField;
        
        private string rutField;
        
        private string fecha_nacimientoField;
        
        private string usernameField;
        
        private string contrasenaField;
        
        private string emailField;
        
        private string direccionField;
        
        private string ciudadField;
        
        private int numero_telefonoField;
        
        private string fecha_creacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Apaterno {
            get {
                return this.apaternoField;
            }
            set {
                this.apaternoField = value;
                this.RaisePropertyChanged("Apaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Amaterno {
            get {
                return this.amaternoField;
            }
            set {
                this.amaternoField = value;
                this.RaisePropertyChanged("Amaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Fecha_nacimiento {
            get {
                return this.fecha_nacimientoField;
            }
            set {
                this.fecha_nacimientoField = value;
                this.RaisePropertyChanged("Fecha_nacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
                this.RaisePropertyChanged("Contrasena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("Direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
                this.RaisePropertyChanged("Ciudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int Numero_telefono {
            get {
                return this.numero_telefonoField;
            }
            set {
                this.numero_telefonoField = value;
                this.RaisePropertyChanged("Numero_telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Fecha_creacion {
            get {
                return this.fecha_creacionField;
            }
            set {
                this.fecha_creacionField = value;
                this.RaisePropertyChanged("Fecha_creacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceClienteSoapChannel : CapaGUI.ServiceCliente.WebServiceClienteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceClienteSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceCliente.WebServiceClienteSoap>, CapaGUI.ServiceCliente.WebServiceClienteSoap {
        
        public WebServiceClienteSoapClient() {
        }
        
        public WebServiceClienteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceClienteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceClienteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceClienteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void webAnadirCliente(CapaGUI.ServiceCliente.Cliente cliente) {
            base.Channel.webAnadirCliente(cliente);
        }
        
        public System.Threading.Tasks.Task webAnadirClienteAsync(CapaGUI.ServiceCliente.Cliente cliente) {
            return base.Channel.webAnadirClienteAsync(cliente);
        }
        
        public System.Data.DataSet webMostrarDatosCliente(string rut) {
            return base.Channel.webMostrarDatosCliente(rut);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> webMostrarDatosClienteAsync(string rut) {
            return base.Channel.webMostrarDatosClienteAsync(rut);
        }
        
        public System.Data.DataSet webIniciarSesionCliente(string usuario) {
            return base.Channel.webIniciarSesionCliente(usuario);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> webIniciarSesionClienteAsync(string usuario) {
            return base.Channel.webIniciarSesionClienteAsync(usuario);
        }
        
        public System.Data.DataSet webMostrarTodosClientes() {
            return base.Channel.webMostrarTodosClientes();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> webMostrarTodosClientesAsync() {
            return base.Channel.webMostrarTodosClientesAsync();
        }
        
        public System.Data.DataSet webMostrarClienteFiltro(string filtro) {
            return base.Channel.webMostrarClienteFiltro(filtro);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> webMostrarClienteFiltroAsync(string filtro) {
            return base.Channel.webMostrarClienteFiltroAsync(filtro);
        }
        
        public void webActualizarPrestamosMultas(string rut) {
            base.Channel.webActualizarPrestamosMultas(rut);
        }
        
        public System.Threading.Tasks.Task webActualizarPrestamosMultasAsync(string rut) {
            return base.Channel.webActualizarPrestamosMultasAsync(rut);
        }
    }
}
